# Site settings
title: Madhusudan Banik
email: msbanik@gmail.com
description: > 
  Madhusudan Banik
baseurl: ""
url: "http://msbanik.com" 
twitter_username: msbanik
github_username: msbanik

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

kramdown:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]